apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: hpa-scaler
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: hpa-scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hpa-scaler
subjects:
- kind: ServiceAccount
  name: default
  namespace: dev
